- name: Install Apache on Web server
  hosts: 
    - web1
  tasks:
    - name: Install Apache server
      apt:
        name: apache2
        state: present
        update_cache: yes
      become: true

    - name: Start apache server
      service: 
        name: apache2
        state: started
        enabled: yes
      become: true